version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: circleci/node:12-browsers
jobs:
  karma-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo testing puissance4!
          npm install
          
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - store_test_results:
          path: /test-results

workflows:
  my-custom-workflow:
    jobs:
      - karma-test